---
language: python
services: docker
env:
  global:
    - ROLE_NAME: bind
  matrix:
    - MOLECULE_DISTRO: ubuntu1804
      MOLECULE_SCENARIO: default
    - MOLECULE_DISTRO: ubuntu1604
      MOLECULE_SCENARIO: default
    - MOLECULE_DISTRO: ubuntu1404
      MOLECULE_SCENARIO: default
    - MOLECULE_DISTRO: debian10
      MOLECULE_SCENARIO: default
    - MOLECULE_DISTRO: debian9
      MOLECULE_SCENARIO: default
    - MOLECULE_DISTRO: ubuntu1804
      MOLECULE_SCENARIO: primarymaster
    - MOLECULE_DISTRO: ubuntu1604
      MOLECULE_SCENARIO: primarymaster
    - MOLECULE_DISTRO: ubuntu1404
      MOLECULE_SCENARIO: primarymaster
    - MOLECULE_DISTRO: debian10
      MOLECULE_SCENARIO: primarymaster
    - MOLECULE_DISTRO: debian9
      MOLECULE_SCENARIO: primarymaster

install:
  - pip install testinfra==3.0.4 molecule docker

script:
  - molecule test --scenario-name $MOLECULE_SCENARIO

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/?branch=master
